### ISSUE TITLE
Move the bots

### ISSUE THREAD

**Issue by JustGuardian** [AlexProgrammerDE/ServerWrecker#145] opened 2023-07-08 12:06 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe your feature request

I'd like that the bots could walk randomly or even run so we can have more specific values for the server stress-test.

**Comment by AlexProgrammerDE** [comment] 2023-07-08 13:47
Duplicate of #140

**Closed by AlexProgrammerDE** 2023-07-08 13:47 UTC
Labels: type: :bulb: enhancement
